services:
  duo2api:
    build:
      context: .
    container_name: duo2api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./config.json:/app/config.json
    environment:
      PYTHONUNBUFFERED: "1"
